name: music_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


#---------PACKAGES-------------#
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Product Specific Packages
  another_flushbar: ^1.12.30  # for creating custom message bar
  flutter_svg: ^2.1.0
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  logger: ^2.5.0

#---------./ PACKAGES-------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/  # Directory for images
    - assets/audio/   # Directory for audio files
    - assets/logo/  # Directory for logo files



  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/synefont.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobsterfont.ttf
 
