// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiZWaMYzQAIDfQLZOAdljpZ94_A9JBHI',
    appId: '1:238661659981:web:267a77b55b2ab4e5629b04',
    messagingSenderId: '238661659981',
    projectId: 'music-app-375b1',
    authDomain: 'music-app-375b1.firebaseapp.com',
    storageBucket: 'music-app-375b1.firebasestorage.app',
    measurementId: 'G-1LZ7S31V6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYrUioFkvptDqox3E4C25WMl-bsGtnmkY',
    appId: '1:238661659981:android:6f937ce491763a43629b04',
    messagingSenderId: '238661659981',
    projectId: 'music-app-375b1',
    storageBucket: 'music-app-375b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmlyWcHYN5hD6Z1gpe7QOQGnvZTP302U',
    appId: '1:238661659981:ios:599115196d07ef57629b04',
    messagingSenderId: '238661659981',
    projectId: 'music-app-375b1',
    storageBucket: 'music-app-375b1.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjmlyWcHYN5hD6Z1gpe7QOQGnvZTP302U',
    appId: '1:238661659981:ios:599115196d07ef57629b04',
    messagingSenderId: '238661659981',
    projectId: 'music-app-375b1',
    storageBucket: 'music-app-375b1.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeiZWaMYzQAIDfQLZOAdljpZ94_A9JBHI',
    appId: '1:238661659981:web:097db7b49c0d7a3b629b04',
    messagingSenderId: '238661659981',
    projectId: 'music-app-375b1',
    authDomain: 'music-app-375b1.firebaseapp.com',
    storageBucket: 'music-app-375b1.firebasestorage.app',
    measurementId: 'G-WD5F65E5GT',
  );
}
